export const FETCH_CONTACTS_PENDING = 'FETCH_CONTACTS_PENDING'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'

export const CREATE_CONTACT_PENDING = 'CREATE_CONTACT_PENDING'
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS'

export const DELETE_CONTACT_PENDING = 'DELETE_CONTACT_PENDING'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'

export const UPDATE_CONTACT_PENDING = 'UPDATE_CONTACT_PENDING'
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'

// export const UPDATE_CONTACT = 'UPDATE_CONTACT's
